### ISSUE TITLE
App crashing after some seconds (unknown reason)

### ISSUE THREAD

**Issue by romuloalves** [ssbc/scuttle-shell#10]
I installed the plugin globally (`npm install -g scuttle-shell`) and executed it with `scuttleshell`.
The icon appears and a few seconds later it crashes.

<img width="179" alt="image" src="https://user-images.githubusercontent.com/3952526/44533316-ae70cc80-a6cb-11e8-826b-1a5b17582cab.png">

```
/usr/local/lib/node_modules/scuttle-shell/node_modules/muxrpc-validation/index.js:59
      if (err) throw err
               ^
UsageError: Param 0 is required
    at new ZE (/usr/local/lib/node_modules/scuttle-shell/node_modules/zerr/index.js:11:42)
    at Object.ZError [as MissingParam] (/usr/local/lib/node_modules/scuttle-shell/node_modules/zerr/index.js:13:14)
    at validate (/usr/local/lib/node_modules/scuttle-shell/node_modules/muxrpc-validation/index.js:122:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/scuttle-shell/node_modules/muxrpc-validation/index.js:58:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/scuttle-shell/node_modules/secret-stack/util.js:80:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/scuttle-shell/node_modules/hoox/index.js:3:17)
    at Object.hooked [as add] (/usr/local/lib/node_modules/scuttle-shell/node_modules/hoox/index.js:10:15)
    at Socket.<anonymous> (/usr/local/lib/node_modules/scuttle-shell/node_modules/scuttlebot/plugins/local.js:59:21)
    at Socket.emit (events.js:180:13)
    at Socket.<anonymous> (/usr/local/lib/node_modules/scuttle-shell/node_modules/broadcast-stream/index.js:51:12)
```

**Comment by romuloalves** [comment]
Of course!
`17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64`

Node: `v9.9.0`

**Comment by carlthuringer** [comment]
Ok, you're actually on macOS, with the same kernel as me. Are you running any other software attempting to connect to the scuttle shell? I still need more steps to reproduced what's happening.

**Comment by romuloalves** [comment]
@carlthuringer 
The people on Scuttlebutt identified it as an scuttlebot error! I've just remembered the thread: [%25bZay5jbXcIbNT8joIeeXWbg80i%2BvR3tgM%2FKpE%2FF8j2s%3D.sha256](https://viewer.scuttlebo t.io/%25bZay5jbXcIbNT8joIeeXWbg80i%2BvR3tgM%2FKpE%2FF8j2s%3D.sha256).

I tested and the problem is not happening at this time!

**Comment by cryptix** [comment]
> I tested and the problem is not happening at this time!
