### ISSUE TITLE
[ERROR] - windows install fails

### ISSUE THREAD

**Issue by mixmix** [ssbc/scuttle-shell#19]
When I try and install the `master` branch on windows 10, I see errors.
I see y'all are working on windows install, this is mainly just providing extra info in case it's useful. If this is redundant info, please feel free to close this.

Seems like there are 2 errors :

## 1.
```
Exception Error: ENOENT: no such file or directory, chmod 'C:\Users\mixmix\projects\patchbay-builder\app\node_modules\forked-systray\systrayhelper.exe'
```

## 2. 
```
C:\Users\mixmix\projects\patchbay-builder\app\node_modules\scuttle-shell\scripts\check-configuration-win.js:20
    let manifestPath = results[key].values[""].value
                                          ^

TypeError: Cannot read property '' of undefined
```

**Comment by mixmix** [comment]
full log : 

```
PS C:\Users\mixmix\projects\patchbay-builder\app> npm i scuttle-shell

> forked-systray@3.0.10 preinstall C:\Users\mixmix\projects\patchbay-builder\app\node_modules\forked-systray
> node ./scripts/fetch-prebuilt-helper.js

systrayhelper not installed!
trying to fetching prebuilt for: win32
donload location: C:\Users\mixmix\AppData\Local\Temp\node-systray-downloadHelper
===========================================================================================================================================================================--------
finished dowloading
start unzip
finished unzip
testing execution
usage: systrayhelper
        send&receive json over stdio to create menu items, etc.

Version 0.0.4 (ded1f2ed4d30f6ca2c89a13db0bd3046c6d6d0f9 built 2018-10-20T17:27:08Z)
helper started succesful!
Exception Error: ENOENT: no such file or directory, chmod 'C:\Users\mixmix\projects\patchbay-builder\app\node_modules\forked-systray\systrayhelper.exe'

> leveldown@4.0.1 install C:\Users\mixmix\projects\patchbay-builder\app\node_modules\secure-scuttlebutt\node_modules\leveldown
> prebuild-install || node-gyp rebuild


> scuttle-shell@0.1.1 install C:\Users\mixmix\projects\patchbay-builder\app\node_modules\scuttle-shell
> node scripts/install.js

C:\Users\mixmix\projects\patchbay-builder\app\node_modules\scuttle-shell\scripts\check-configuration-win.js:20
    let manifestPath = results[key].values[""].value
                                          ^

TypeError: Cannot read property '' of undefined
    at regedit.list (C:\Users\mixmix\projects\patchbay-builder\app\node_modules\scuttle-shell\scripts\check-configuration-win.js:20:43)
    at C:\Users\mixmix\projects\patchbay-builder\app\node_modules\regedit\index.js:243:13
    at ChildProcess.exithandler (child_process.js:262:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:545:12)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scuttle-shell@0.1.1 install: `node scripts/install.js`
npm ERR! Exit status 1
```

**Comment by mixmix** [comment]
Using the `windowsInstall` branch I see only error `1.` ... but starting patchbay with this scuttle-shell works _fine_!!

well done

**Comment by mixmix** [comment]
NOOOOO cc @christianbundy
Is there a way to stop the robot via email?

**Comment by mixmix** [comment]
maybe it was resolved. I'll make a fresh issue if it comes up again

**Comment by christianbundy** [comment]
Sorry, I think emails can stop it but they don't re-open.

A few solutions to keep this from happening:

- Currently you can vouch for an issue by assigning yourself to it (my favorite)
  - Gives me the ability to vouch for issues by other people
  - Keeps me accountable by showing that I'm the one keeping it open
  - Lets me unassign myself from issues where others may want to keep it open
- We have the option of adding people to a whitelist so that their issues are never closed
- We can totally nuke stale[bot] if it's a persistent headache
- ??? I'm open to any other solutions and happy to dedicate some time toward them
