### ISSUE TITLE
[Error] macOS app start fails

### ISSUE THREAD

**Issue by abelaska** [ssbc/scuttle-shell#21]
OK, I've tried to start master scuttle-shell on macOS 10.13.6 and it kind a failed. Here's install console output.

```shell
$ git clone https://github.com/ssbc/scuttle-shell
$ cd scuttle-shell
$ git log --name-status HEAD^..HEAD
commit a92c57de0633279e5c7b710ddc0869ab8b1e05c1 (HEAD -> master, origin/master, origin/HEAD)
Author: Christian Bundy <christianbundy@fraction.io>
Date:   Thu Nov 1 08:44:25 2018 -0700

    Add config for Stale app

A       .github/stale.yml
$ npm ci
> sodium-native@2.2.2 install /Users/abelaska/Downloads/scuttle-shell/node_modules/sodium-native
> node-gyp-build "node preinstall.js" "node postinstall.js"


> leveldown@4.0.1 install /Users/abelaska/Downloads/scuttle-shell/node_modules/ssb-unread/node_modules/leveldown
> prebuild-install || node-gyp rebuild


> level@4.0.0 postinstall /Users/abelaska/Downloads/scuttle-shell/node_modules/ssb-unread/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate


> leveldown@3.0.2 install /Users/abelaska/Downloads/scuttle-shell/node_modules/leveldown
> prebuild-install || node-gyp rebuild


> level@3.0.2 postinstall /Users/abelaska/Downloads/scuttle-shell/node_modules/level
> opencollective-postinstall || exit 0

Thank you for using level!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/level/donate


> fsevents@1.2.4 install /Users/abelaska/Downloads/scuttle-shell/node_modules/fsevents
> node install

[fsevents] Success: "/Users/abelaska/Downloads/scuttle-shell/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> forked-systray@3.0.8 preinstall /Users/abelaska/Downloads/scuttle-shell/node_modules/forked-systray
> node ./scripts/fetch-prebuilt-helper.js

systrayhelper not installed!
trying to fetching prebuilt for: darwin
donload location: /var/folders/r9/nxwj64ds2556ptj46schl3300000gn/T/node-systray-downloadHelper
===============================================================================================================================================================================================================================================================================
finished untar
testing execution
usage: systrayhelper
	send&receive json over stdio to create menu items, etc.

Version 0.0.3 (0953942245566bf358ba937af840947100380e15 built 2018-09-13T19:08:04Z)
helper started succesful!
Exception Error: ENOENT: no such file or directory, unlink '/var/folders/r9/nxwj64ds2556ptj46schl3300000gn/T/node-systray-downloadHelper'

> scuttle-shell@0.1.1 install /Users/abelaska/Downloads/scuttle-shell
> node scripts/install.js

[OK] Wrote manifest path to registry.
[INFO] Try: npm run check
[INFO] App manifest path location: /Users/abelaska/Library/Application Support/Mozilla/NativeMessagingHosts/scuttleshell.json
[OK] Configuration appears correct
[INFO] App located at: /Users/abelaska/Downloads/scuttle-shell/host-app.js
added 738 packages in 25.427s
```

And this is the error I get when I try to start the app.

```shell
$ npm start

> scuttle-shell@0.1.1 start /Users/abelaska/Downloads/scuttle-shell
> node server.js

started sbot server v13.0.0
ssb-friends: stream legacy api used
NotFoundError: Key not found in database [startedAt]
    at /Users/abelaska/Downloads/scuttle-shell/node_modules/ssb-unread/node_modules/levelup/lib/levelup.js:160:15
    at /Users/abelaska/Downloads/scuttle-shell/node_modules/ssb-unread/node_modules/encoding-down/index.js:51:21
systrayhelper 0.0.3 (0953942245566bf358ba937af840947100380e15 built 2018-09-13T19:08:04Z)
panic: runtime error: index out of range

goroutine 36 [running]:
main.onReady.func2.1(0xc420016600, 0xb, 0xc420015080, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/ssbc/systrayhelper/tray.go:111 +0x187
main.onReady.func2.3(0xc420016600, 0xb, 0xc420015080, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/travis/gopath/src/github.com/ssbc/systrayhelper/tray.go:152 +0x155
main.onReady.func2.4(0xc42016c000, 0xc42016a0e0)
	/Users/travis/gopath/src/github.com/ssbc/systrayhelper/tray.go:177 +0x69
created by main.onReady.func2
	/Users/travis/gopath/src/github.com/ssbc/systrayhelper/tray.go:167 +0x344
scuttle-shell got exit: { code: 2, signal: null }
```

How can I help more?

**Comment by cryptix** [comment]
Ah.. sorry, somehow you got v0.0.3 of the systrayhelper. This shouldn’t happen with 0.0.4 or a newer version of forked-systray - I guess some package locked it down.

**Comment by cryptix** [comment]
Yes, bumping forked-systray to patch 9 and running `npm I` again should make this work.

**Comment by abelaska** [comment]
ok, I confirm that switching "forked-systray" to "^3.0.10" followed by `npm i` fixed the problem.

**Comment by mixmix** [comment]
This is a duplicate of https://github.com/ssbc/scuttle-shell/issues/20 I think

I noticed using the `windowsInstall` branch worked to get 0.0.4
But then there's still an error
