### ISSUE TITLE
Failed to fetch pre-built systrayhelper

### ISSUE THREAD

**Issue by physkets** [ssbc/scuttle-shell#31]
When I try to install the latest version, it fails with the following error:

```
> forked-systray@3.0.11 preinstall /home/user/AUR/Temp/src/scuttle-shell/node_modules/forked-systray
> node ./scripts/fetch-prebuilt-helper.js

systrayhelper not installed!
trying to fetching prebuilt for: linux
donload location: /tmp/node-systray-downloadHelper
===============================================================================================================================================================================================
finished untar
testing execution
/tmp/node-systray-unpack/systrayhelper: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory
Error: Command failed: /tmp/node-systray-unpack/systrayhelper --test
/tmp/node-systray-unpack/systrayhelper: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at testExecutable (/home/user/AUR/Temp/src/scuttle-shell/node_modules/forked-systray/scripts/fetch-prebuilt-helper.js:96:5)
    at Extract.<anonymous> (/home/user/AUR/Temp/src/scuttle-shell/node_modules/forked-systray/scripts/fetch-prebuilt-helper.js:85:9)
    at Extract.emit (events.js:333:22)
    at finishMaybe (/home/user/AUR/Temp/src/scuttle-shell/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at /home/user/AUR/Temp/src/scuttle-shell/node_modules/readable-stream/lib/_stream_writable.js:608:5
    at Extract._final (/home/user/AUR/Temp/src/scuttle-shell/node_modules/tar-stream/extract.js:255:3)
    at callFinal (/home/user/AUR/Temp/src/scuttle-shell/node_modules/readable-stream/lib/_stream_writable.js:601:10)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  status: 127,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 74 6d 70 2f 6e 6f 64 65 2d 73 79 73 74 72 61 79 2d 75 6e 70 61 63 6b 2f 73 79 73 74 72 61 79 68 65 6c 70 65 72 3a 20 65 72 72 6f 72 20 77 68 69 6c ... 109 more bytes>
  ],
  pid: 14291,
  stdout: <Buffer >,
  stderr: <Buffer 2f 74 6d 70 2f 6e 6f 64 65 2d 73 79 73 74 72 61 79 2d 75 6e 70 61 63 6b 2f 73 79 73 74 72 61 79 68 65 6c 70 65 72 3a 20 65 72 72 6f 72 20 77 68 69 6c ... 109 more bytes>
}

######
Hello, sorry you had to see this...

Failed to fetch pre-built systrayhelper.
  Most likely the combination of OS and Architecture isn't currently supported.
  
  To still get this working you will have to do some console-magic...
  
  1) Install Go - See https://golang.org/doc/install
  1.5) On linux: you need two libraries, listed here: https://github.com/getlantern/systray#platform-specific-concerns
  2) run this command: go get github.com/ssbc/systrayhelper
  3) sudo mv $HOME/go/bin/systrayhelper /usr/local/bin (or any other folder, as long as it's in your $PATH)
  
  TODO: evaluate falling back to https://github.com/chemdrew/npm-golang
  TODO: brew.sh and windows snoop templates installing the helper
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forked-systray@3.0.11 preinstall: `node ./scripts/fetch-prebuilt-helper.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the forked-systray@3.0.11 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-02-07T18_38_07_103Z-debug.log
```

**Comment by cryptix** [comment]
`systrayhelper: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory`

Is the problem here: are you on Linux? If so which? This should be solvable by installing the library. See the package bakes here: https://github.com/ssbc/systrayhelper/blob/master/README.md#installation

**Comment by physkets** [comment]
Yes, so I installed `systrayhelper` directly as a separate package, and it was detected during installation. 

Actually running `scuttleshell` failed though, but that is a separate issue.
